package Modelo;
// Generated 04-sep-2016 17:29:32 by Hibernate Tools 4.3.1

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {

     private String email;
     private String contrasena;

    public Usuarios() {
    }

    public Usuarios(String email, String contrasena) {
       this.email = email;
       this.contrasena = contrasena;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
}